twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        uploads_img: '%kernel.root_dir%/../web/bundles/SmallAdsBundle/uploads_img'
